name: minimap_scrollbar
description: "A Flutter widget that provides a minimap scrollbar for easy navigation within a scrollable area."
version: 0.1.0
repository: https://github.com/Davies-K/minimap_scrollbar
homepage: https://github.com/davies-k
topics: ["scrollbar", "minimapscrollbar", "scroll", "scrollable", "minimapscrollbar"]
funding: [https://buymeacoffee.com/davieskwarteng]

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
