name: example
description: "A new Flutter project."
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  minimap_scrollbar: 
    path: ../..
  super_editor: ^0.2.7
  code_text_field: ^1.1.0
  highlight: ^0.7.0
  flutter_highlight: ^0.7.0
  google_fonts: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/memoji/